use sql1231230;

DROP TABLE allowed_user;
DROP TABLE answer;
DROP TABLE choice;
DROP TABLE question;
DROP TABLE poll;
DROP TABLE confirmation_token;
DROP TABLE `user`;

CREATE TABLE `user`
(
  USER_ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  EMAIL VARCHAR(50) NOT NULL UNIQUE,
  PW VARCHAR(60) NOT NULL,
  IS_ENABLED BOOLEAN NOT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE confirmation_token
(
	TOKEN_ID INT NOT NULL AUTO_INCREMENT,
    CONFIRMATION_TOKEN VARCHAR(255),
    EXPIRATION_DATE DATETIME NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (TOKEN_ID),
    FOREIGN KEY (USER_ID) REFERENCES `user`(USER_ID)
);

CREATE TABLE poll
(
  POLL_ID INT NOT NULL AUTO_INCREMENT,
  CREATOR_ID INT NOT NULL,
  CREATION_DATE DATETIME NOT NULL,
  EXPIRATION_DATE DATETIME NOT NULL,
  DOUBLE_ROUND BOOLEAN NOT NULL,
  CLASSIFIED BOOLEAN NOT NULL,
  ISOPEN BOOLEAN NOT NULL,
  PRIMARY KEY (POLL_ID),
  FOREIGN KEY (CREATOR_ID) REFERENCES `user`(USER_ID)
);

CREATE TABLE question
(
  QUESTION_ID INT NOT NULL AUTO_INCREMENT,
  POLL_ID INT NOT NULL,
  EXPIRATION_DATE DATETIME,
  IS_OPEN BOOLEAN,
  QTEXT VARCHAR(255) NOT NULL,
  PRIMARY KEY (QUESTION_ID),
  FOREIGN KEY (POLL_ID) REFERENCES poll(POLL_ID)
);

CREATE TABLE choice
(
  CHOICE_ID INT NOT NULL AUTO_INCREMENT,
  QUESTION_ID INT NOT NULL,
  CTEXT VARCHAR(255) NOT NULL,
  PRIMARY KEY (CHOICE_ID),
  FOREIGN KEY (QUESTION_ID) REFERENCES question(QUESTION_ID)
);

CREATE TABLE answer
(
  ANSWER_ID INT NOT NULL AUTO_INCREMENT,
  POLL_ID INT NOT NULL,
  QUESTION_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  CHOICE_ID INT NOT NULL,
  CASTING_TIME DATETIME NOT NULL,
  PRIMARY KEY (ANSWER_ID),
  FOREIGN KEY (POLL_ID) REFERENCES poll(POLL_ID),
  FOREIGN KEY (CHOICE_ID) REFERENCES choice(CHOICE_ID),
  FOREIGN KEY (QUESTION_ID) REFERENCES question(QUESTION_ID),
  FOREIGN KEY (USER_ID) REFERENCES `user`(USER_ID)
);

CREATE TABLE allowed_user
(
  USER_ID INT NOT NULL,
  POLL_ID INT NOT NULL,
  PRIMARY KEY (USER_ID, POLL_ID),
  FOREIGN KEY (USER_ID) REFERENCES `user`(USER_ID),
  FOREIGN KEY (POLL_ID) REFERENCES poll(POLL_ID)
);
